/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated.admin.categorias'
import { Route as AuthenticatedAdminAjustesRouteImport } from './routes/_authenticated.admin.ajustes'
import { Route as AuthenticatedAdminProductosIndexRouteImport } from './routes/_authenticated.admin.productos.index'
import { Route as AuthenticatedAdminProductosNuevoRouteImport } from './routes/_authenticated.admin.productos.nuevo'
import { Route as AuthenticatedAdminProductosIdRouteImport } from './routes/_authenticated.admin.productos.$id'

const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjustesRoute =
  AuthenticatedAdminAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosIndexRoute =
  AuthenticatedAdminProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosNuevoRoute =
  AuthenticatedAdminProductosNuevoRouteImport.update({
    id: '/productos/nuevo',
    path: '/productos/nuevo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosIdRoute =
  AuthenticatedAdminProductosIdRouteImport.update({
    id: '/productos/$id',
    path: '/productos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/producto/$id': typeof ProductoIdRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/productos/$id': typeof AuthenticatedAdminProductosIdRoute
  '/admin/productos/nuevo': typeof AuthenticatedAdminProductosNuevoRoute
  '/admin/productos/': typeof AuthenticatedAdminProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/productos/$id': typeof AuthenticatedAdminProductosIdRoute
  '/admin/productos/nuevo': typeof AuthenticatedAdminProductosNuevoRoute
  '/admin/productos': typeof AuthenticatedAdminProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/contacto': typeof ContactoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/producto/$id': typeof ProductoIdRoute
  '/_authenticated/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/productos/$id': typeof AuthenticatedAdminProductosIdRoute
  '/_authenticated/admin/productos/nuevo': typeof AuthenticatedAdminProductosNuevoRoute
  '/_authenticated/admin/productos/': typeof AuthenticatedAdminProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/categorias'
    | '/contacto'
    | '/admin'
    | '/producto/$id'
    | '/admin/ajustes'
    | '/admin/categorias'
    | '/admin/'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/categorias'
    | '/contacto'
    | '/producto/$id'
    | '/admin/ajustes'
    | '/admin/categorias'
    | '/admin'
    | '/admin/productos/$id'
    | '/admin/productos/nuevo'
    | '/admin/productos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalogo'
    | '/categorias'
    | '/contacto'
    | '/_authenticated/admin'
    | '/producto/$id'
    | '/_authenticated/admin/ajustes'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/productos/$id'
    | '/_authenticated/admin/productos/nuevo'
    | '/_authenticated/admin/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  CategoriasRoute: typeof CategoriasRoute
  ContactoRoute: typeof ContactoRoute
  ProductoIdRoute: typeof ProductoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajustes': {
      id: '/_authenticated/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AuthenticatedAdminAjustesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos/': {
      id: '/_authenticated/admin/productos/'
      path: '/productos'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AuthenticatedAdminProductosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos/nuevo': {
      id: '/_authenticated/admin/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AuthenticatedAdminProductosNuevoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos/$id': {
      id: '/_authenticated/admin/productos/$id'
      path: '/productos/$id'
      fullPath: '/admin/productos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAjustesRoute: typeof AuthenticatedAdminAjustesRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductosIdRoute: typeof AuthenticatedAdminProductosIdRoute
  AuthenticatedAdminProductosNuevoRoute: typeof AuthenticatedAdminProductosNuevoRoute
  AuthenticatedAdminProductosIndexRoute: typeof AuthenticatedAdminProductosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAjustesRoute: AuthenticatedAdminAjustesRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductosIdRoute: AuthenticatedAdminProductosIdRoute,
  AuthenticatedAdminProductosNuevoRoute: AuthenticatedAdminProductosNuevoRoute,
  AuthenticatedAdminProductosIndexRoute: AuthenticatedAdminProductosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  CategoriasRoute: CategoriasRoute,
  ContactoRoute: ContactoRoute,
  ProductoIdRoute: ProductoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
